name: Django CI

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/django-ci.yml"

jobs:
  backend:
    name: Backend (Django)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    concurrency:
      group: backend-${{ github.ref }}
      cancel-in-progress: true
    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      IS_DEV: "True"
      SECRET_KEY: test-secret

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django sanity checks
        run: python manage.py check

      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test --verbosity=2
